### PR TITLE
Update to fprime 2.0.1

### PR DESCRIPTION
**Pull request by kevin-f-ortega**
Merging with master.

### CODE REVIEW

**Comment by arizvi786** [comment]
@kevin-f-ortega please assign this PR to me.

**Review by arizvi786 — COMMENTED** [review]
@kevin-f-ortega why are the GTestBase and TesterBase files being removed for ADC UT?

**Comment by kevin-f-ortega** [comment]
GTestBase and TesterBase files are not needed since the cmake system auto generates those files for you. I plan to get rid of the GTestBase and TesterBase files from other components in a different PR. The reason to remove them is to avoid polluting the repo with auto generated files.

**Comment by kevin-f-ortega** [comment]
Ran these changes on a sphinx. Software came up and I was able to command software. Good to merge. Also, @arizvi786, please take a look at https://github.com/fprime-community/fprime-sphinx/pull/2 too.

**Review by arizvi786 — APPROVED** [review]

**Comment by arizvi786** [comment]
@kevin-f-ortega you should be able to merge this now, I don't have write access to the repo.

**Pull request merged**
